# Generated by Django 5.2.1 on 2025-06-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_publication'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
