# Generated by Django 5.2.1 on 2025-06-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_userprofile_admin_reponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], default='fr', max_length=2, verbose_name="Langue de l'article"),
        ),
    ]
